nama_produk = input("Nama Produk = ")
harga = input("Harga = ")
jumlah_beli = input("Jumlah Beli = ")
maka_bayar = input("Maka Bayar = ")
ppn = input("PPN = ")
total  = input("Total = ")
tunai = input ("Tunai = ")
kembalian = input("Kembalian = ")

print("========================================")
print("Alfamart Pondok Labu Jakara Selatan")
print("========================================")
print("Nama Produk = " +str(nama_produk))
print("Harga = " +str(harga))
print("Jumlah Beli = " +str(jumlah_beli))
print("Maka Bayar = " +str(maka_bayar))
print("PPN = " +str(ppn))
print("=====================================(+)")
print("Total = " +str(total))
print("Tunai = " +str(tunai))
print("=====================================(-)")
print("Kembalian = " +str(kembalian))
print("========================================")
print("Terima Kasih")
print("----------------------------------------")