print("=+=+=+=+ Data Diri Mahasiswa =+=+=+=+")
nim = input("NIM : ")
nama = input("Nama : ")
jurusan = input("Jurusan : ")
alamat = input("Alamat : ")

print("Hasil Cetak data diatas adalah")
print("Nim : " +str(nim))
print("Nama : " +str(nama))
print("Jurusan : " +str(jurusan))
print("Alamat : " +str(alamat))